# Generated by Django 5.1.4 on 2026-05-22 19:44

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_appearancesettings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': "Un utilisateur avec ce nom d'utilisateur existe déjà."}, help_text='Requis. 150 caractères maximum. Uniquement des lettres, nombres, espaces et les caractères « @ », « . », « + », « - » et « _ ».', max_length=150, unique=True, validators=[apps.accounts.models.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
