# Generated by Django 5.1.4 on 2026-09-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
        ('clubs', '0016_clubmatch_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_category',
            field=models.ForeignKey(blank=True, help_text='Si sélectionné, ce coach ne pourra gérer que cette catégorie.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.category', verbose_name='Catégorie (Entraîneur) / الفئة (للمدرب)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur / مدير'), ('organizer', 'Organisateur / منظم'), ('manager', "Responsable d'équipe / مسؤول فريق"), ('coach', 'Entraîneur / مدرب'), ('viewer', 'Spectateur / متفرج')], default='viewer', max_length=20, verbose_name='Rôle'),
        ),
    ]
