# Generated by Django 5.1.4 on 2026-05-04 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_id_alter_team_id_alter_team_logo'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='groupstanding',
            options={'verbose_name': 'Classement groupe', 'verbose_name_plural': 'Classements groupes'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-year', '-edition'], 'verbose_name': 'Tournoi', 'verbose_name_plural': 'Tournois'},
        ),
        migrations.AlterModelOptions(
            name='tournamentteam',
            options={'ordering': ['seed', 'team__name'], 'verbose_name': 'Participation', 'verbose_name_plural': 'Participations'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Début inscriptions'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='groups', to='teams.team', verbose_name='Équipes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='drawn',
            field=models.PositiveIntegerField(default=0, verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='goals_against',
            field=models.PositiveIntegerField(default=0, verbose_name='BC'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='goals_for',
            field=models.PositiveIntegerField(default=0, verbose_name='BP'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupstanding_set', to='tournaments.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='lost',
            field=models.PositiveIntegerField(default=0, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='played',
            field=models.PositiveIntegerField(default=0, verbose_name='J'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Pts'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='groupstanding',
            name='won',
            field=models.PositiveIntegerField(default=0, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('group_knockout', 'Groupes + Élimination directe'), ('round_robin', 'Championnat aller-retour'), ('single_knockout', 'Élimination directe')], default='group_knockout', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(default='Stade Communal', max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(default=16, verbose_name='Nb. max équipes'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_groups',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de groupes'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='points_draw',
            field=models.PositiveIntegerField(default=1, verbose_name='Points nul'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='points_loss',
            field=models.PositiveIntegerField(default=0, verbose_name='Points défaite'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='points_win',
            field=models.PositiveIntegerField(default=3, verbose_name='Points victoire'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Clôture inscriptions'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_tournaments', to='teams.team', verbose_name='Finaliste'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('registration', 'Inscriptions ouvertes'), ('group_stage', 'Phase de groupes'), ('knockout', 'Phase finale'), ('finished', 'Terminé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournaments', through='tournaments.TournamentTeam', to='teams.team', verbose_name='Équipes'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams_advancing_per_group',
            field=models.PositiveIntegerField(default=2, verbose_name='Équipes qualifiées/groupe'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trophies', to='teams.team', verbose_name='Vainqueur'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='eliminated_at_stage',
            field=models.CharField(blank=True, max_length=20, verbose_name='Éliminée en'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmée'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='seed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tête de série'),
        ),
    ]
