# Generated by Django 5.1.4 on 2026-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_group_options_alter_groupstanding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes/Motif'),
        ),
    ]
