# Generated by Django 5.1.4 on 2026-05-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_cover_photo'),
        ('tournaments', '0004_alter_tournamentteam_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='teams.team'),
        ),
    ]
