# Generated by Django 5.1.4 on 2026-05-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentteam_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstanding',
            name='goal_difference',
            field=models.IntegerField(default=0, verbose_name='DB'),
        ),
    ]
