# Generated by Django 5.1.4 on 2026-06-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_groupstanding_goal_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Frais d'inscription / مبلغ الاشتراك"),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé / المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Paiement validé / تم تأكيد الدفع'),
        ),
        migrations.CreateModel(
            name='TournamentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre / المصاريف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant / المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date / التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / ملاحظات')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tournaments.tournament', verbose_name='Tournoi')),
            ],
            options={
                'verbose_name': 'Dépense Tournoi',
                'verbose_name_plural': 'Dépenses Tournois',
                'ordering': ['-date'],
            },
        ),
    ]
