# Generated by Django 5.1.4 on 2026-06-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_subscription_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant / المبلغ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date / التاريخ')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes / ملاحظات')),
                ('tournament_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tournaments.tournamentteam', verbose_name='Participation')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Source / الإيرادات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant / المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date / التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / ملاحظات')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='tournaments.tournament', verbose_name='Tournoi')),
            ],
            options={
                'verbose_name': 'Recette Tournoi',
                'verbose_name_plural': 'Recettes Tournois',
                'ordering': ['-date'],
            },
        ),
    ]
