# Generated by Django 5.1.4 on 2026-06-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_teampaymenttransaction_tournamentrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet / الاسم الكامل')),
                ('role', models.CharField(choices=[('president', 'رئيس اللجنة / Président'), ('vice_president', 'نائب الرئيس / Vice-Président'), ('treasurer', 'أمين المال / Trésorier'), ('secretary', 'الأمين العام / Secrétaire'), ('technical', 'المدير التقني / Directeur Technique'), ('media', 'مسؤول الإعلام / Chargé Médias'), ('security', 'مسؤول الأمن / Responsable Sécurité'), ('member', 'عضو / Membre')], default='member', max_length=30, verbose_name='Rôle / المنصب')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='committee/', verbose_name='Photo / الصورة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone / الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email / البريد الإلكتروني')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance / تاريخ الميلاد')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name="Date d'adhésion / تاريخ الانضمام")),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='N° Identité / رقم الهوية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre / الترتيب')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / ملاحظات')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='tournaments.tournament', verbose_name='Tournoi / الدورة')),
            ],
            options={
                'verbose_name': 'Membre du comité / عضو اللجنة',
                'verbose_name_plural': 'Membres du comité / أعضاء اللجنة',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
