# Generated by Django 5.1.4 on 2026-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_add_vice_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(choices=[('president', 'رئيس اللجنة / Président'), ('vice_president', 'نائب الرئيس / Vice-Président'), ('treasurer', 'أمين المال / Trésorier'), ('vice_treasurer', 'نائب أمين المال / Vice-Trésorier'), ('secretary', 'الكاتب العام / Secrétaire Général'), ('vice_secretary', 'نائب الكاتب العام / Vice-Secrétaire'), ('technical', 'المدير التقني / Directeur Technique'), ('media', 'مسؤول الإعلام / Chargé Médias'), ('security', 'مسؤول الأمن / Responsable Sécurité'), ('medical', 'مسؤول طبي / Responsable Médical'), ('member', 'عضو / Membre')], default='member', max_length=30, verbose_name='Rôle / المنصب'),
        ),
    ]
