# Generated by Django 5.1.4 on 2026-07-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_alter_committeemember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstanding',
            options={'ordering': ['-points', '-goal_difference', '-goals_for', 'id'], 'verbose_name': 'Classement groupe', 'verbose_name_plural': 'Classements groupes'},
        ),
    ]
