# Generated by Django 5.1.4 on 2026-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'application / شعار التطبيق"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_name',
            field=models.CharField(default='TurniQ', max_length=100, verbose_name="Nom de l'application / اسم التطبيق"),
        ),
    ]
