# Generated by Django 5.1.4 on 2026-08-22 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la catégorie (ex: U8, U10, Seniors)')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge minimum')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge maximum')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['min_age', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du match')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('opponent', models.CharField(max_length=100, verbose_name='Adversaire')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('is_home', models.BooleanField(default=True, verbose_name='À domicile')),
                ('our_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Notre score')),
                ('their_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Leur score')),
                ('notes', models.TextField(blank=True, verbose_name='Compte-rendu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='clubs.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Match du Club',
                'verbose_name_plural': 'Matchs du Club',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ClubPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clubs/players/', verbose_name='Photo')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Groupe sanguin')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='clubs/medical/', verbose_name='Certificat médical')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du tuteur (Parent)')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du tuteur')),
                ('player_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du joueur')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Poste')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de maillot')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('card_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Numéro de carte')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clubs.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Joueur du Club',
                'verbose_name_plural': 'Joueurs du Club',
                'ordering': ['category', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('location', models.CharField(default='Stade Communal', max_length=100, verbose_name='Lieu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Objectifs')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='clubs.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': "Séance d'entraînement",
                'verbose_name_plural': "Séances d'entraînement",
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Présent')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Remarques')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clubs.clubplayer', verbose_name='Joueur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clubs.trainingsession', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('session', 'player')},
            },
        ),
    ]
