# Generated by Django 5.1.4 on 2026-08-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='نادي الوفاق الرياضي', max_length=100, verbose_name='Nom du Club')),
                ('club_subtitle', models.CharField(default='أكاديمية كرة القدم - مسلمون', max_length=100, verbose_name='Sous-titre')),
                ('club_abbreviation', models.CharField(default='WRM', max_length=10, verbose_name='Abréviation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/settings/', verbose_name='Logo du Club')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='clubs/settings/', verbose_name='Image de couverture')),
                ('gradient_start', models.CharField(default='from-primary/80', max_length=20, verbose_name='Couleur de début (Gradient)')),
                ('gradient_end', models.CharField(default='to-black/90', max_length=20, verbose_name='Couleur de fin (Gradient)')),
            ],
            options={
                'verbose_name': 'Paramètres du Club',
                'verbose_name_plural': 'Paramètres du Club',
            },
        ),
    ]
