# Generated by Django 5.1.4 on 2026-08-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=100, verbose_name='Type de blessure')),
                ('date_of_injury', models.DateField(verbose_name='Date de blessure')),
                ('expected_return', models.DateField(blank=True, null=True, verbose_name='Retour prévu le')),
                ('is_recovered', models.BooleanField(default=False, verbose_name='Rétabli ?')),
                ('notes', models.TextField(blank=True, verbose_name='Diagnostic et traitement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clubs.clubplayer', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Dossier Médical (Blessure)',
                'verbose_name_plural': 'Dossiers Médicaux (Blessures)',
                'ordering': ['-date_of_injury'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('role', models.CharField(choices=[('COACH', 'Entraîneur (مدرب)'), ('ADMIN', 'Administrateur (إداري)'), ('MEDIC', 'Staff Médical (طبيب/معالج)'), ('KITMAN', 'Responsable Matériel (مكلف بالعتاد)')], default='COACH', max_length=10, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clubs/staff/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='clubs.category', verbose_name='Catégorie Assignée (Optionnel)')),
            ],
            options={
                'verbose_name': 'Membre du Staff',
                'verbose_name_plural': 'Membres du Staff',
                'ordering': ['role', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Sélectionnez le 1er jour du mois concerné', verbose_name='Mois (ex: 2026-09-01 pour Septembre)')),
                ('amount', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8, verbose_name='Montant (DA)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé ?')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clubs.clubplayer', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Abonnement Mensuel',
                'verbose_name_plural': 'Abonnements Mensuels',
                'ordering': ['-month', 'player__last_name'],
                'unique_together': {('player', 'month')},
            },
        ),
    ]
