# Generated by Django 5.1.4 on 2026-08-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_medicalrecord_staffmember_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingattendance',
            options={'ordering': ['session__date', 'player__last_name'], 'verbose_name': "Présence à l'entraînement", 'verbose_name_plural': 'Présences aux entraînements'},
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='reason_for_absence',
            field=models.CharField(blank=True, max_length=200, verbose_name="Motif d'absence"),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='Présent ?'),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clubs.trainingsession', verbose_name="Séance d'entraînement"),
        ),
        migrations.CreateModel(
            name='PlayerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_training_kit', models.BooleanField(default=False, verbose_name="Tenue d'entraînement reçue")),
                ('training_kit_date', models.DateField(blank=True, null=True, verbose_name='Date tenue entraînement')),
                ('received_tracksuit', models.BooleanField(default=False, verbose_name='Survêtement (Parade) reçu')),
                ('tracksuit_date', models.DateField(blank=True, null=True, verbose_name='Date survêtement')),
                ('received_bag', models.BooleanField(default=False, verbose_name='Sac de sport reçu')),
                ('bag_date', models.DateField(blank=True, null=True, verbose_name='Date sac')),
                ('notes', models.TextField(blank=True, verbose_name="Notes sur l'équipement")),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='clubs.clubplayer', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Équipement du Joueur',
                'verbose_name_plural': 'Équipements des Joueurs',
            },
        ),
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluated', models.DateField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('physical_fitness', models.IntegerField(default=5, verbose_name='Condition Physique /10')),
                ('speed', models.IntegerField(default=5, verbose_name='Vitesse /10')),
                ('passing', models.IntegerField(default=5, verbose_name='Passes & Contrôle /10')),
                ('tactical_awareness', models.IntegerField(default=5, verbose_name='Sens Tactique /10')),
                ('discipline', models.IntegerField(default=5, verbose_name='Discipline & Assiduité /10')),
                ('coach_remarks', models.TextField(blank=True, verbose_name='Remarques du Coach')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.staffmember', verbose_name='Évaluateur')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clubs.clubplayer', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Évaluation du Joueur',
                'verbose_name_plural': 'Évaluations des Joueurs',
                'ordering': ['-date_evaluated'],
            },
        ),
    ]
