# Generated by Django 5.1.4 on 2026-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_trainingattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coach_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entraîneur (اسم المدرب)'),
        ),
        migrations.AddField(
            model_name='category',
            name='coach_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de l'entraîneur (رقم هاتف المدرب)"),
        ),
    ]
