# Generated by Django 5.1.4 on 2026-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_category_coach_name_category_coach_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('U6', 'U6 (أقل من 6 سنوات)'), ('U7', 'U7 (أقل من 7 سنوات)'), ('U8', 'U8 (أقل من 8 سنوات)'), ('U9', 'U9 (أقل من 9 سنوات)'), ('U10', 'U10 (أقل من 10 سنوات)'), ('U11', 'U11 (أقل من 11 سنة)'), ('U12', 'U12 (أقل من 12 سنة)'), ('U13', 'U13 (أقل من 13 سنة)'), ('U14', 'U14 (أقل من 14 سنة)'), ('U15', 'U15 (أقل من 15 سنة)'), ('U17', 'U17 (أقل من 17 سنة)'), ('U19', 'U19 (أقل من 19 سنة)'), ('U20', 'U20 (أقل من 20 سنة)'), ('U21', 'U21 (أقل من 21 سنة)'), ('U23', 'U23 (أقل من 23 سنة)'), ('Seniors', 'Seniors (أكابر)'), ('Féminines', 'Féminines (إناث)'), ('École de Football', 'École de Football (مدرسة كروية)')], max_length=50, verbose_name='Nom de la catégorie (اسم الفئة العمرية)'),
        ),
    ]
