# Generated by Django 5.1.4 on 2026-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='president_name',
            field=models.CharField(default='بيرم نصرالدين', max_length=100, verbose_name='اسم رئيس النادي'),
        ),
    ]
