# Generated by Django 5.1.4 on 2026-08-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_clubsettings_president_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayer',
            name='position',
            field=models.CharField(blank=True, choices=[('حارس مرمى', 'حارس مرمى (Gardien de but)'), ('مدافع', 'مدافع (Défenseur)'), ('وسط ميدان', 'وسط ميدان (Milieu de terrain)'), ('مهاجم', 'مهاجم (Attaquant)')], default='وسط ميدان', max_length=50, verbose_name='Poste (المركز التكتيكي)'),
        ),
    ]
