# Generated by Django 5.1.4 on 2026-09-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_clubplayer_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubplayer',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence (هاتف الطوارئ)"),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille en cm (القامة)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='medical_history',
            field=models.TextField(blank=True, verbose_name='Antécédents médicaux (الأمراض المزمنة أو السوابق الجراحية)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du tuteur (البريد الإلكتروني)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='parent_profession',
            field=models.CharField(blank=True, max_length=150, verbose_name='Profession et lieu de travail (المهنة ومقر العمل)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('أب', 'أب (Père)'), ('أم', 'أم (Mère)'), ('وصي شرعي', 'وصي شرعي (Tuteur Légal)')], max_length=30, verbose_name='Lien de parenté (صلة القرابة)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('يمنى', 'يمنى (Droitier)'), ('يسرى', 'يسرى (Gaucher)'), ('كلاهما', 'كلاهما (Ambidextre)')], max_length=20, verbose_name='Pied Fort (القدم المفضلة)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='previous_club',
            field=models.CharField(blank=True, max_length=150, verbose_name='Club précédent (النادي أو المدرسة السابقة)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='school_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Niveau Scolaire (المستوى الدراسي)'),
        ),
        migrations.AddField(
            model_name='clubplayer',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Poids en kg (الوزن)'),
        ),
        migrations.AlterField(
            model_name='clubplayer',
            name='position',
            field=models.CharField(blank=True, choices=[('حارس مرمى', 'حارس مرمى (Gardien de but)'), ('مدافع', 'مدافع (Défenseur)'), ('وسط ميدان', 'وسط ميدان (Milieu de terrain)'), ('مهاجم', 'مهاجم (Attaquant)')], max_length=50, verbose_name='Poste (المركز التكتيكي)'),
        ),
    ]
