# Generated by Django 5.1.4 on 2026-09-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_clubplayer_emergency_phone_clubplayer_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='academy_registration_open',
            field=models.BooleanField(default=False, verbose_name='Ouverture des inscriptions (فتح التسجيلات)'),
        ),
    ]
