# Generated by Django 5.1.4 on 2026-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clubsettings_academy_registration_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre / العنوان')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Contenu / المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/news/', verbose_name='Image / صورة')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publie / منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualite du Club',
                'verbose_name_plural': 'Actualites du Club',
                'ordering': ['-created_at'],
            },
        ),
    ]
