# Generated by Django 5.1.4 on 2026-09-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_clubnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmatch',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='matches_called', to='clubs.clubplayer', verbose_name='Joueurs Convoqués'),
        ),
    ]
