# Generated by Django 5.1.4 on 2026-10-10 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_clubmatch_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'équipe / اسم الفريق")),
                ('code', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='league_teams/')),
            ],
            options={
                'verbose_name': 'Equipe de Ligue',
                'verbose_name_plural': 'Equipes de Ligue',
            },
        ),
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('U15', 'U15'), ('U17', 'U17'), ('U20', 'U20')], default='U17', max_length=50)),
                ('round_number', models.IntegerField(default=1, verbose_name='Journée / الجولة')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('is_played', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='clubs.leagueteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='clubs.leagueteam')),
            ],
            options={
                'verbose_name': 'Match de Ligue',
                'verbose_name_plural': 'Matchs de Ligue',
                'ordering': ['round_number', 'date'],
            },
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('U15', 'U15'), ('U17', 'U17'), ('U20', 'U20')], default='U17', max_length=50)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='clubs.leagueteam')),
            ],
            options={
                'ordering': ['-points', '-goals_for'],
                'unique_together': {('team', 'category')},
            },
        ),
    ]
