# Generated by Django 5.1.4 on 2026-05-04 08:03

import apps.teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Format recommandé : carré, PNG/JPG, 200×200px minimum', null=True, upload_to=apps.teams.models.team_logo_path, verbose_name='Logo du club'),
        ),
    ]
