# Generated by Django 5.1.4 on 2026-05-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_id_alter_team_id_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
