# Generated by Django 5.1.4 on 2026-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, default='MESSLMOUNE', max_length=100, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='team',
            name='wilaya',
            field=models.CharField(blank=True, default='Tipaza', max_length=100, verbose_name='Wilaya'),
        ),
    ]
