# Generated by Django 5.1.4 on 2026-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_city_alter_team_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_starter',
            field=models.BooleanField(default=False, verbose_name='Titulaire'),
        ),
        migrations.AddField(
            model_name='player',
            name='lineup_x',
            field=models.FloatField(default=50.0, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='player',
            name='lineup_y',
            field=models.FloatField(default=50.0, verbose_name='Position Y'),
        ),
        migrations.AddField(
            model_name='team',
            name='preferred_formation',
            field=models.CharField(default='4-3-3', help_text='Ex: 4-3-3, 4-4-2, 3-5-2', max_length=10, verbose_name='Formation préférée'),
        ),
    ]
