# Generated by Django 5.1.4 on 2026-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_player_is_starter_player_lineup_x_player_lineup_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Format recommandé : paysage, PNG/JPG, 1920×1080px minimum (Optionnel)', null=True, upload_to='teams/covers/', verbose_name='Photo de couverture'),
        ),
    ]
