# Generated by Django 5.1.4 on 2026-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='banner_height',
            field=models.PositiveIntegerField(default=550, verbose_name='Hauteur de la bannière (px)'),
        ),
        migrations.AddField(
            model_name='team',
            name='cover_offset_y',
            field=models.IntegerField(default=50, help_text='0=Haut, 50=Centre, 100=Bas', verbose_name="Position verticale de l'image (%)"),
        ),
    ]
