# Generated by Django 5.1.4 on 2026-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_banner_height_team_cover_offset_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Capitaine'),
        ),
    ]
