# Generated by Django 5.1.4 on 2026-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_player_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, verbose_name='Abréviation'),
        ),
        migrations.AddField(
            model_name='team',
            name='french_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom en Français'),
        ),
    ]
