# Generated by Django 5.1.4 on 2026-07-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_abbreviation_team_french_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='suspension_matches_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de matchs de suspension'),
        ),
        migrations.AddField(
            model_name='player',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Raison de la suspension'),
        ),
    ]
