# Generated by Django 5.1.4 on 2026-05-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('match_result', 'Résultat de match'), ('match_reminder', 'Rappel de match'), ('suspension', 'Suspension de joueur'), ('tournament', 'Annonce du tournoi'), ('injury', 'Blessure signalée'), ('team_registration', "Inscription d'équipe")], max_length=20),
        ),
    ]
