# Generated by Django 5.1.4 on 2026-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('match_result', 'Résultat de match'), ('match_reminder', 'Rappel de match'), ('suspension', 'Suspension de joueur'), ('tournament', 'Annonce du tournoi'), ('injury', 'Blessure signalée'), ('team_registration', "Inscription d'équipe"), ('user_registration', "Demande d'adhésion"), ('system', 'Système')], max_length=20),
        ),
    ]
