# Generated by Django 5.1.4 on 2026-05-06 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0006_team_cover_photo'),
        ('tournaments', '0004_alter_tournamentteam_tournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['match', 'minute'], 'verbose_name': 'Carton', 'verbose_name_plural': 'Cartons'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['match', 'minute'], 'verbose_name': 'But', 'verbose_name_plural': 'Buts'},
        ),
        migrations.AlterModelOptions(
            name='injury',
            options={'ordering': ['-injury_date'], 'verbose_name': 'Blessure', 'verbose_name_plural': 'Blessures'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'verbose_name': 'Arbitre', 'verbose_name_plural': 'Arbitres'},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('yellow', 'Carton jaune'), ('red', 'Carton rouge'), ('yellow_red', '2ème jaune → rouge')], max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='matches.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='card',
            name='minute',
            field=models.PositiveIntegerField(verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='teams.player', verbose_name='Joueur'),
        ),
        migrations.AlterField(
            model_name='card',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raison'),
        ),
        migrations.AlterField(
            model_name='card',
            name='results_in_suspension',
            field=models.BooleanField(default=False, verbose_name='Entraîne une suspension'),
        ),
        migrations.AlterField(
            model_name='card',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_received', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='teams.player', verbose_name='Passeur décisif'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('own_goal', 'But contre son camp'), ('penalty', 'Penalty'), ('free_kick', 'Coup franc direct'), ('header', 'Tête')], default='normal', max_length=15, verbose_name='Type de but'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_extra_time',
            field=models.BooleanField(default=False, verbose_name='Prolongation'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='minute',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.player', verbose_name='Buteur'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='absence_weeks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Semaines d'absence estimées"),
        ),
        migrations.AlterField(
            model_name='injury',
            name='actual_return',
            field=models.DateField(blank=True, null=True, verbose_name='Retour effectif'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, verbose_name='Partie du corps'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='expected_return',
            field=models.DateField(blank=True, null=True, verbose_name='Retour estimé'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='injury_date',
            field=models.DateField(verbose_name='Date de blessure'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='injury_type',
            field=models.CharField(choices=[('muscle', 'Musculaire'), ('ligament', 'Ligamentaire'), ('bone', 'Osseuse (fracture)'), ('contusion', 'Contusion'), ('head', 'Crâne / tête'), ('other', 'Autre')], max_length=15, verbose_name="Type d'blessure"),
        ),
        migrations.AlterField(
            model_name='injury',
            name='is_recovered',
            field=models.BooleanField(default=False, verbose_name='Guéri'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injuries', to='matches.match', verbose_name='Lors du match'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='teams.player', verbose_name='Joueur'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='severity',
            field=models.CharField(choices=[('minor', 'Mineure (< 1 sem.)'), ('moderate', 'Modérée (1-4 sem.)'), ('severe', 'Grave (> 4 sem.)'), ('career', 'Fin de saison')], max_length=10, verbose_name='Gravité'),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_day',
            field=models.PositiveIntegerField(default=1, verbose_name='Journée'),
        ),
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='matches.match', verbose_name='Match suivant (bracket)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='match',
            name='penalties_team1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TAB Éq. 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='penalties_team2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TAB Éq. 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.referee', verbose_name='Arbitre'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Tour'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team1',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score Éq. 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team2',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score Éq. 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('GROUP', 'Phase de groupes'), ('R16', 'Huitièmes de finale'), ('QF', 'Quarts de finale'), ('SF', 'Demi-finales'), ('TP', 'Match pour la 3e place'), ('FINAL', 'Finale')], default='GROUP', max_length=10, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmé'), ('live', 'En cours'), ('finished', 'Terminé'), ('postponed', 'Reporté'), ('cancelled', 'Annulé')], default='scheduled', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='Équipe 1 (domicile)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='Équipe 2 (extérieur)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(default='Stade Communal', max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='referee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Licence'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='MatchMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image/Photo'), ('video', 'Vidéo'), ('link', 'Lien (YouTube, etc.)')], default='image', max_length=10, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre / Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='match_media/%Y/%m/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='matches.match', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Média du match',
                'verbose_name_plural': 'Médias des matchs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
