# Generated by Django 5.1.4 on 2026-05-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_card_options_alter_goal_options_and_more'),
        ('teams', '0006_team_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=6.0, help_text='Note de 0 à 10', max_digits=4, verbose_name="Note de l'arbitre")),
                ('is_man_of_the_match', models.BooleanField(default=False, verbose_name='Homme du match')),
                ('notes', models.TextField(blank=True, verbose_name='Commentaires')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='teams.player')),
            ],
            options={
                'verbose_name': 'Performance joueur',
                'verbose_name_plural': 'Performances joueurs',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
