# Generated by Django 5.1.4 on 2026-05-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_playermatchperformance'),
        ('teams', '0006_team_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='featured_player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_matches_home', to='teams.player', verbose_name='Joueur vedette (Éq. 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='featured_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_matches_away', to='teams.player', verbose_name='Joueur vedette (Éq. 2)'),
        ),
    ]
