# Generated by Django 5.1.4 on 2026-05-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_featured_player1_match_featured_player2'),
        ('teams', '0007_team_banner_height_team_cover_offset_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='Équipe 1 (domicile)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='Équipe 2 (extérieur)'),
        ),
    ]
