# Generated by Django 5.1.4 on 2026-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchperformance',
            name='is_man_of_the_match',
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='is_starter',
            field=models.BooleanField(default=False, verbose_name='Titulaire'),
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='position_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Poste (ex: GK, LW)'),
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='x_pos',
            field=models.FloatField(default=50.0, verbose_name='Position X (%)'),
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='y_pos',
            field=models.FloatField(default=50.0, verbose_name='Position Y (%)'),
        ),
    ]
