# Generated by Django 5.1.4 on 2026-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_remove_playermatchperformance_is_man_of_the_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='promo_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Config Promo'),
        ),
    ]
