# Generated by Django 5.1.4 on 2026-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_promo_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='referees/', verbose_name='Photo / الصورة'),
        ),
    ]
