# Generated by Django 5.1.4 on 2026-06-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_referee_photo'),
        ('teams', '0008_player_is_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_votes', to='teams.player')),
            ],
            options={
                'verbose_name': 'Vote Match',
                'verbose_name_plural': 'Votes Matchs',
                'constraints': [models.UniqueConstraint(fields=('match', 'user_ip'), name='unique_ip_vote_per_match')],
            },
        ),
    ]
