# Generated by Django 5.1.4 on 2026-06-25 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_matchvote'),
        ('teams', '0008_player_is_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.PositiveIntegerField(default=0, verbose_name='Minute actuelle'),
        ),
        migrations.AddField(
            model_name='match',
            name='current_period',
            field=models.CharField(choices=[('1H', '1ère Mi-temps / الشوط الأول'), ('HT', 'Mi-temps / الاستراحة'), ('2H', '2ème Mi-temps / الشوط الثاني'), ('OT', 'Prolongation / الشوط الإضافي'), ('PK', 'Tirs au but / ركلات الترجيح')], default='1H', max_length=20, verbose_name='Période actuelle'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('kickoff', "Coup d'envoi / ركلة البداية"), ('halftime', 'Mi-temps / الاستراحة'), ('second_half', 'Seconde période / الشوط الثاني'), ('fulltime', 'Fin du match / نهاية المباراة'), ('substitution', 'Changement / تبديل'), ('var', 'Décision VAR / قرار الفار'), ('penalty_missed', 'Penalty manqué / ركلة جزاء ضائعة'), ('commentary', 'Commentaire / تعليق')], default='commentary', max_length=20, verbose_name="Type d'événement")),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minute')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description (FR)')),
                ('description_ar', models.CharField(blank=True, max_length=255, verbose_name='Description (AR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='matches.match', verbose_name='Match')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_primary', to='teams.player', verbose_name='Joueur principal')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_secondary', to='teams.player', verbose_name='Joueur secondaire (ex: entrant)')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='teams.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Événement de match',
                'verbose_name_plural': 'Événements de match',
                'ordering': ['minute', 'created_at'],
            },
        ),
    ]
