# Generated by Django 5.1.4 on 2026-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_current_minute_match_current_period_matchevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='forfeit_reason',
            field=models.TextField(blank=True, verbose_name='Motif du forfait / سبب الأعتذار أو الغياب'),
        ),
        migrations.AddField(
            model_name='match',
            name='forfeit_type',
            field=models.CharField(choices=[('NONE', 'Aucun / مباراة عادية'), ('TEAM1', 'Forfait Équipe 1 / غياب الفريق الأول (فوز الفريق 2 بنتيجة 3-0)'), ('TEAM2', 'Forfait Équipe 2 / غياب الفريق الثاني (فوز الفريق 1 بنتيجة 3-0)'), ('BOTH', 'Forfait Double / غياب الفريقين معاً (خسارة كلا الفريقين 0-0)')], default='NONE', max_length=10, verbose_name='Type de forfait / نوع الغياب والاعتذار'),
        ),
        migrations.AddField(
            model_name='match',
            name='official_report_notes',
            field=models.TextField(blank=True, verbose_name='Remarques officielles / ملاحظات تقرير الحكم واللجنة المنظمة'),
        ),
    ]
