# Generated by Django 5.1.4 on 2026-07-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_forfeit_reason_match_forfeit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='suspension_matches',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de matchs de suspension'),
        ),
    ]
