# Generated by Django 5.1.4 on 2026-08-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_card_suspension_matches'),
        ('teams', '0010_player_suspension_matches_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='man_of_the_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man_of_the_match_awards', to='teams.player', verbose_name='Homme du match / رجل المباراة'),
        ),
    ]
